project_id = "pzcecjuxiorqcmbtiipq"

[functions.generate-job-description]
verify_jwt = false

[functions.suggest-job-categories]
verify_jwt = false

[functions.generate-resume]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false

[functions.calculate-job-match]
verify_jwt = false

[functions.generate-audio-resume]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.bulk-import-categories]
verify_jwt = false

[functions.salary-insights]
verify_jwt = false

[functions.ai-location-suggest]
verify_jwt = false

[functions.ai-career-buddy]
verify_jwt = false

[functions.ai-candidate-insights]
verify_jwt = false