import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { FileText, Mail, Download, Loader2, Calendar, TrendingUp, CheckCircle2 } from 'lucide-react';
import { motion } from 'framer-motion';
import jsPDF from 'jspdf';

interface AnalyticsReportExportProps {
  employerId: string;
  employerName: string;
}

interface ReportData {
  totalViews: number;
  totalApplications: number;
  totalInterviews: number;
  totalHired: number;
  conversionRate: string;
  interviewRate: string;
  hireRate: string;
  jobs: { title: string; views: number; applications: number; interviews: number; hired: number }[];
  weekRange: string;
}

async function fetchReportData(employerId: string): Promise<ReportData> {
  const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
  const now = new Date().toISOString();

  const { data: jobs } = await supabase
    .from('jobs')
    .select('id, title, view_count, is_active, status')
    .eq('employer_id', employerId)
    .limit(50);

  const jobRows = await Promise.all(
    (jobs || []).map(async (job) => {
      const [{ count: appCount }, { count: interviewCount }] = await Promise.all([
        supabase.from('applications').select('*', { count: 'exact', head: true }).eq('job_id', job.id),
        supabase.from('interviews').select('*', { count: 'exact', head: true }).eq('job_id', job.id),
      ]);
      const { count: hiredCount } = await supabase
        .from('applications').select('*', { count: 'exact', head: true })
        .eq('job_id', job.id).eq('status', 'hired');

      return {
        title: job.title,
        views: job.view_count || 0,
        applications: appCount || 0,
        interviews: interviewCount || 0,
        hired: hiredCount || 0,
      };
    })
  );

  const totalViews = jobRows.reduce((s, j) => s + j.views, 0);
  const totalApplications = jobRows.reduce((s, j) => s + j.applications, 0);
  const totalInterviews = jobRows.reduce((s, j) => s + j.interviews, 0);
  const totalHired = jobRows.reduce((s, j) => s + j.hired, 0);

  const weekStart = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  const weekEnd = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

  return {
    totalViews,
    totalApplications,
    totalInterviews,
    totalHired,
    conversionRate: totalViews > 0 ? ((totalApplications / totalViews) * 100).toFixed(1) : '0',
    interviewRate: totalApplications > 0 ? ((totalInterviews / totalApplications) * 100).toFixed(1) : '0',
    hireRate: totalInterviews > 0 ? ((totalHired / totalInterviews) * 100).toFixed(1) : '0',
    jobs: jobRows.sort((a, b) => b.applications - a.applications).slice(0, 15),
    weekRange: `${weekStart} – ${weekEnd}`,
  };
}

function generatePDF(data: ReportData, companyName: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFillColor(66, 133, 244);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Hiring Analytics Report', 14, 18);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`${companyName} • ${data.weekRange}`, 14, 28);
  doc.text('Generated by Hire for Job', 14, 35);

  y = 52;
  doc.setTextColor(0, 0, 0);

  // Funnel summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Hiring Funnel Overview', 14, y);
  y += 10;

  const funnelStages = [
    { label: 'Total Views', value: data.totalViews, rate: null },
    { label: 'Applications', value: data.totalApplications, rate: `${data.conversionRate}% from views` },
    { label: 'Interviews', value: data.totalInterviews, rate: `${data.interviewRate}% from applications` },
    { label: 'Hired', value: data.totalHired, rate: `${data.hireRate}% from interviews` },
  ];

  doc.setFontSize(10);
  funnelStages.forEach((stage) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${stage.label}:`, 14, y);
    doc.setFont('helvetica', 'normal');
    doc.text(`${stage.value.toLocaleString()}`, 60, y);
    if (stage.rate) {
      doc.setTextColor(100, 100, 100);
      doc.text(`(${stage.rate})`, 85, y);
      doc.setTextColor(0, 0, 0);
    }
    y += 7;
  });

  y += 6;

  // Conversion bars
  doc.setFillColor(230, 240, 255);
  doc.roundedRect(14, y, pageWidth - 28, 22, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Overall Funnel Conversion', 20, y + 8);
  doc.setFont('helvetica', 'normal');
  const overallConversion = data.totalViews > 0
    ? ((data.totalHired / data.totalViews) * 100).toFixed(2) : '0';
  doc.text(`Views → Hired: ${overallConversion}%`, 20, y + 16);
  y += 32;

  // Job breakdown table
  if (data.jobs.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Job Performance Breakdown', 14, y);
    y += 8;

    // Table header
    doc.setFillColor(245, 245, 245);
    doc.rect(14, y, pageWidth - 28, 8, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('Job Title', 16, y + 5.5);
    doc.text('Views', 100, y + 5.5);
    doc.text('Apps', 120, y + 5.5);
    doc.text('Interviews', 140, y + 5.5);
    doc.text('Hired', 168, y + 5.5);
    doc.text('Conv %', 185, y + 5.5);
    y += 10;

    doc.setFont('helvetica', 'normal');
    data.jobs.forEach((job, i) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      if (i % 2 === 0) {
        doc.setFillColor(250, 250, 250);
        doc.rect(14, y - 4, pageWidth - 28, 7, 'F');
      }
      const title = job.title.length > 35 ? job.title.slice(0, 35) + '…' : job.title;
      const conv = job.views > 0 ? ((job.applications / job.views) * 100).toFixed(1) + '%' : '—';
      doc.text(title, 16, y);
      doc.text(String(job.views), 100, y);
      doc.text(String(job.applications), 120, y);
      doc.text(String(job.interviews), 140, y);
      doc.text(String(job.hired), 168, y);
      doc.text(conv, 185, y);
      y += 7;
    });
  }

  // Footer
  y = doc.internal.pageSize.getHeight() - 12;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Hire for Job — hireforjob1.lovable.app', 14, y);
  doc.text(`Generated ${new Date().toLocaleString()}`, pageWidth - 70, y);

  doc.save(`hiring-report-${new Date().toISOString().split('T')[0]}.pdf`);
}

export function AnalyticsReportExport({ employerId, employerName }: AnalyticsReportExportProps) {
  const [loading, setLoading] = useState(false);
  const [emailing, setEmailing] = useState(false);
  const [weeklyEnabled, setWeeklyEnabled] = useState(false);

  const handleDownloadPDF = async () => {
    setLoading(true);
    try {
      const data = await fetchReportData(employerId);
      generatePDF(data, employerName);
      toast.success('Report downloaded!');
    } catch (e) {
      toast.error('Failed to generate report');
    } finally {
      setLoading(false);
    }
  };

  const handleEmailReport = async () => {
    setEmailing(true);
    try {
      const { data: session } = await supabase.auth.getSession();
      const res = await fetch(
        `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/employer-analytics-report`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${session.session?.access_token}`,
          },
          body: JSON.stringify({ employer_id: employerId }),
        }
      );
      if (!res.ok) throw new Error('Failed');
      toast.success('Analytics report emailed to you!');
    } catch {
      toast.error('Failed to send email report');
    } finally {
      setEmailing(false);
    }
  };

  return (
    <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}>
      <Card className="rounded-xl border-border/50">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center">
                <FileText className="w-4.5 h-4.5 text-primary" />
              </div>
              <div>
                <CardTitle className="text-sm font-semibold">Analytics Reports</CardTitle>
                <CardDescription className="text-xs">Download or email your hiring funnel data</CardDescription>
              </div>
            </div>
            <Badge variant="secondary" className="text-[10px]">
              <Calendar className="w-3 h-3 mr-1" />
              Weekly
            </Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Funnel Preview */}
          <div className="grid grid-cols-4 gap-2">
            {[
              { label: 'Views', icon: TrendingUp, color: 'text-primary' },
              { label: 'Applied', icon: FileText, color: 'text-success' },
              { label: 'Interview', icon: Calendar, color: 'text-warning' },
              { label: 'Hired', icon: CheckCircle2, color: 'text-success' },
            ].map((stage, i) => (
              <div key={stage.label} className="text-center">
                <div className="flex items-center justify-center mb-1">
                  <stage.icon className={`w-4 h-4 ${stage.color}`} />
                </div>
                <p className="text-[10px] text-muted-foreground">{stage.label}</p>
                {i < 3 && (
                  <div className="absolute right-0 top-1/2 -translate-y-1/2 text-muted-foreground/30">→</div>
                )}
              </div>
            ))}
          </div>

          {/* Actions */}
          <div className="flex gap-2">
            <Button
              size="sm"
              className="flex-1 gap-1.5 rounded-xl text-xs h-9"
              onClick={handleDownloadPDF}
              disabled={loading}
            >
              {loading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
              Download PDF
            </Button>
            <Button
              size="sm"
              variant="outline"
              className="flex-1 gap-1.5 rounded-xl text-xs h-9"
              onClick={handleEmailReport}
              disabled={emailing}
            >
              {emailing ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Mail className="w-3.5 h-3.5" />}
              Email Report
            </Button>
          </div>

          {/* Weekly toggle */}
          <div className="flex items-center justify-between p-2.5 rounded-lg bg-muted/30">
            <div className="flex items-center gap-2">
              <Mail className="w-3.5 h-3.5 text-muted-foreground" />
              <Label htmlFor="weekly-report" className="text-xs cursor-pointer">Auto-send weekly report</Label>
            </div>
            <Switch
              id="weekly-report"
              checked={weeklyEnabled}
              onCheckedChange={setWeeklyEnabled}
            />
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
}
