
-- Add new columns for comprehensive company profile
ALTER TABLE public.employers
  ADD COLUMN IF NOT EXISTS work_environment text DEFAULT 'onsite',
  ADD COLUMN IF NOT EXISTS relocation_support boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS internship_available boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS fresher_hiring boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS hr_contact_email text,
  ADD COLUMN IF NOT EXISTS careers_page_url text,
  ADD COLUMN IF NOT EXISTS tech_stack text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS key_skills_hiring text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS education_preference text,
  ADD COLUMN IF NOT EXISTS work_culture_type text,
  ADD COLUMN IF NOT EXISTS company_values text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS interview_rounds_count integer,
  ADD COLUMN IF NOT EXISTS hiring_timeline text,
  ADD COLUMN IF NOT EXISTS assessment_types text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS avg_salary_range text,
  ADD COLUMN IF NOT EXISTS bonus_structure text,
  ADD COLUMN IF NOT EXISTS paid_leaves_policy text,
  ADD COLUMN IF NOT EXISTS learning_budget text,
  ADD COLUMN IF NOT EXISTS promotion_frequency text,
  ADD COLUMN IF NOT EXISTS career_growth_paths text,
  ADD COLUMN IF NOT EXISTS employee_retention_rate text,
  ADD COLUMN IF NOT EXISTS diversity_policies text,
  ADD COLUMN IF NOT EXISTS work_life_balance_rating integer,
  ADD COLUMN IF NOT EXISTS awards_recognition text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS office_locations text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS preferred_certifications text[] DEFAULT '{}';
